server:
  port: 80

spring:
  application:
    name: cloud-order-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud-2020?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    password: root
    username: root

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  jta:
    atomikos:
      properties:
        enable-logging:


eureka:
  client:
    service-url:
      # defaultZone: http://eureka7002.com:7002/eureka, http://eureka7001.com:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    prefer-ip-address: true


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always


# 设置Feign客户端超时时间（openFeign默认支持ribbon）
ribbon:
  # 建立连接后 从服务器读取到可用资源所用的时间（首字母必须大写）
  ReadTimeout: 10000
  # 建立连接所用的时间，适用于网络状况正常的情况下，两端连接所有时间（首字母必须大写）
  ConnectTimeout: 2000


# Feign的日志级别
logging:
  level:
    gxc.cloud.service.order.feign: DEBUG