server:
  port: 80

spring:
  application:
    name: cloud-order-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud-2020?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    password: root
    username: root

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect


eureka:
  client:
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka, http://eureka7001.com:7001/eureka
  instance:
    prefer-ip-address: true


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always

logging:
  level:
    root: INFO