server:
  port: 8001

spring:
  application:
    name: cloud-hystrix-payment-service

eureka:
  client:
    service-url:
      #defaultZone: http://eureka7002.com:7002/eureka, http://eureka7001.com:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka
    registry-fetch-interval-seconds: 8 # 定期的更新客户端的服务清单时间为8s
  instance:
    prefer-ip-address: true
    instance-id: payment-hystrix-8001
    lease-renewal-interval-in-seconds: 4  # 每隔这个时间会主动心跳一次，默认值为30s
    lease-expiration-duration-in-seconds: 12 # 设置服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除，一般是lease-renewal-interval-in-seconds的3倍








management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always

logging:
  level:
    root: INFO